
import Card from '@/components/Cards/Card'
import Product from '@/components/Products/Product'

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app'
}

export default function Home() {
  return (
    <main className="">
    <Card />
    <div className="font-bold text-[23px] ml-5 mt-5 p-2 bg-[rgb(0,122,186)] rounded-2xl">PRODUCTS</div>
    <Product />
    </main>
  )
}
